export  const numbers = [
    {
        id: '1',
        audio: require('../../audios/Vocabulario/numbers/one.mp4') ,
        palavra: 'One',
        pronuncia: `/wʌn/` ,
        img: require('../../images/ImgVocabulario/numbers/one.png'),
    },
    {
        id: '2',
        audio: require('../../audios/Vocabulario/numbers/two.mp4') ,
        palavra: 'two',
        pronuncia: `/tuː/` ,
        img: require('../../images/ImgVocabulario/numbers/two.jpg'),
    },
    {
        id: '3',
        audio: require('../../audios/Vocabulario/numbers/three.mp4') ,
        palavra: 'Three',
        pronuncia: `/θriː/` ,
        img: require('../../images/ImgVocabulario/numbers/three.png'),
    },
    {
        id: '4',
        audio: require('../../audios/Vocabulario/numbers/four.mp4') ,
        palavra: 'Four',
        pronuncia: `/fɔːr/` ,
        img: require('../../images/ImgVocabulario/numbers/four.png'),
    },
    {
        id: '5',
        audio: require('../../audios/Vocabulario/numbers/five.mp4') ,
        palavra: 'Five',
        pronuncia: `/faɪv/` ,
        img: require('../../images/ImgVocabulario/numbers/five.png'),
    },
    {
        id: '6',
        audio: require('../../audios/Vocabulario/numbers/six.mp4') ,
        palavra: 'Six',
        pronuncia: `/sɪks/` ,
        img: require('../../images/ImgVocabulario/numbers/six.png'),
    },
    {
        id: '7',
        audio: require('../../audios/Vocabulario/numbers/seven.mp4') ,
        palavra: 'Seven',
        pronuncia: `/ˈsev.ən/` ,
        img: require('../../images/ImgVocabulario/numbers/seven.jpg'),
    },
    {
        id: '8',
        audio: require('../../audios/Vocabulario/numbers/eighth.mp4') ,
        palavra: 'Eighth',
        pronuncia: `/eɪtθ/` ,
        img: require('../../images/ImgVocabulario/numbers/eight.png'),
    },
    {
        id: '9',
        audio: require('../../audios/Vocabulario/numbers/nine.mp4') ,
        palavra: 'Nine',
        pronuncia: `/naɪn/`,
        img: require('../../images/ImgVocabulario/numbers/nine.png'),
    },
    {
        id: '10',
        audio: require('../../audios/Vocabulario/numbers/ten.mp4') ,
        palavra: 'Ten',
        pronuncia: `/ten/`,
        img: require('../../images/ImgVocabulario/numbers/ten.png'),
    },
    
];
export  const animals = [
    {
        id: '1',
        audio: require('../../audios/Vocabulario/animals/Monkey.m4a') ,
        palavra: 'Monkey',
        pronuncia: `/mʌŋ.ki/` ,
        img: require('../../images/ImgVocabulario/animals/monkey.jpg'),
    },
    {
        id: '2',
        audio: require('../../audios/Vocabulario/animals/Horse.m4a') ,
        palavra: 'Horse',
        pronuncia: `/horse/` ,
        img: require('../../images/ImgVocabulario/animals/horse.jpg'),
    },
    {
        id: '3',
        audio: require('../../audios/Vocabulario/animals/Lion.m4a') ,
        palavra: 'Lion',
        pronuncia: `/laɪ.ən/` ,
        img: require('../../images/ImgVocabulario/animals/Lion.jpg'),
    },
    {
        id: '4',
        audio: require('../../audios/Vocabulario/animals/Fish.m4a') ,
        palavra: 'Fish',
        pronuncia: `/fɪʃ/` ,
        img: require('../../images/ImgVocabulario/animals/fish.jpg'),
    },
    {
        id: '5',
        audio: require('../../audios/Vocabulario/animals/Jaguar.m4a') ,
        palavra: 'Jaguar',
        pronuncia: `/dʒæɡ.wɑːr/` ,
        img: require('../../images/ImgVocabulario/animals/Jaguar.jpg'),
    },
    {
        id: '6',
        audio: require('../../audios/Vocabulario/animals/hen.mp4') , // 
        palavra: 'Hen',
        pronuncia: `/hen/` ,
        img: require('../../images/ImgVocabulario/animals/hen.png'),
    },
    {
        id: '7',
        audio: require('../../audios/Vocabulario/animals/Bird.m4a') ,
        palavra: 'Bird',
        pronuncia: `/ˈbɝːd/` ,
        img: require('../../images/ImgVocabulario/animals/bird.jpg'),
    },
    {
        id: '8',
        audio: require('../../audios/Vocabulario/animals/Cat.m4a') ,
        palavra: 'Cat',
        pronuncia: `/kæt/` ,
        img: require('../../images/ImgVocabulario/animals/cat.jpg'),
    },
    {
        id: '9',
        audio: require('../../audios/Vocabulario/animals/Dog.m4a') ,
        palavra: 'Dog',
        pronuncia: `/dɑːɡ/`,
        img: require('../../images/ImgVocabulario/animals/dog.jpg'),
    },
    {
        id: '10',
        audio: require('../../audios/Vocabulario/animals/Zebra.m4a') ,
        palavra: 'Zebra',
        pronuncia: `/ziː.brə/`,
        img: require('../../images/ImgVocabulario/animals/zebra.png'),
    },
    
];
export  const foods= [
    {
        id: '1',
        audio: require('../../audios/Vocabulario/foods/Apple.m4a') ,
        palavra: 'Apple',
        pronuncia: `/æp.ə/` ,
        img: require('../../images/ImgVocabulario/Foods/Apple.png'),
    },
    {
        id: '2',
        audio: require('../../audios/Vocabulario/foods/Cake.m4a') ,
        palavra: 'Cake',
        pronuncia: `/keɪk/` ,
        img: require('../../images/ImgVocabulario/Foods/cake.jpg'),
    },
    {
        id: '3',
        audio: require('../../audios/Vocabulario/foods/Bread.m4a') ,
        palavra: 'Bread',
        pronuncia: `/bred/` ,
        img: require('../../images/ImgVocabulario/Foods/bread.jpg'),
    },
    {
        id: '4',
        audio: require('../../audios/Vocabulario/foods/Coffee.m4a') ,
        palavra: 'Coffee',
        pronuncia: `/kɑː.fi/` ,
        img: require('../../images/ImgVocabulario/Foods/coffee.png'),
    },
    {
        id: '5',
        audio: require('../../audios/Vocabulario/foods/Hamburger.m4a') ,
        palavra: 'Hamburger',
        pronuncia: `/ˈhæmˌbɝː.ɡɚ/` ,
        img: require('../../images/ImgVocabulario/Foods/hamburger.png'),
    },
    {
        id: '6',
        audio: require('../../audios/Vocabulario/foods/Chocolate.m4a') ,
        palavra: 'Chocolate',
        pronuncia: `/tʃɑːk.lə/` ,
        img: require('../../images/ImgVocabulario/Foods/chocolate.png'),
    },
    {
        id: '7',
        audio: require('../../audios/Vocabulario/foods/Candy.m4a') ,
        palavra: 'Candy',
        pronuncia: `/ˈkæn.d/` ,
        img: require('../../images/ImgVocabulario/Foods/candy.jpg'),
    },
    {
        id: '8',
        audio: require('../../audios/Vocabulario/foods/Orange.m4a') ,
        palavra: 'Orange',
        pronuncia: `/ɔːr.ɪndʒ/` ,
        img: require('../../images/ImgVocabulario/Foods/Orange.jpg'),
    },
    {
        id: '9',
        audio: require('../../audios/Vocabulario/foods/Soda.m4a') ,
        palavra: 'Soda',
        pronuncia: `/ˈsoʊ.də/`,
        img: require('../../images/ImgVocabulario/Foods/soda.jpg'),
    },
    {
        id: '10',
        audio: require('../../audios/Vocabulario/foods/spaghetti.mp3') , // corrigir
        palavra: 'Spaghetti',
        pronuncia: `/spəˈɡet̬.i/`,
        img: require('../../images/ImgVocabulario/Foods/spaghetti.jpg'),
    },
    
];
export  const objects = [
    {
        id: '1',
        audio: require('../../audios/Vocabulario/objects/Computer.m4a') ,
        palavra: 'Computer',
        pronuncia: `/kəmˈpjuː.t̬ɚ/` ,
        img: require('../../images/ImgVocabulario/Objects/computer.png'),
    },
    {
        id: '2',
        audio: require('../../audios/Vocabulario/objects/Chair.m4a') ,
        palavra: 'Chair',
        pronuncia: `/tʃer/` ,
        img: require('../../images/ImgVocabulario/Objects/chair.jpg'),
    },
    {
        id: '3',
        audio: require('../../audios/Vocabulario/objects/Doll.m4a') ,
        palavra: 'Doll',
        pronuncia: `/dɑːl/` ,
        img: require('../../images/ImgVocabulario/Objects/Doll.jpg'),
    },
    {
        id: '4',
        audio: require('../../audios/Vocabulario/objects/Pan.m4a') ,
        palavra: 'Pan',
        pronuncia: `/Pan/` ,
        img: require('../../images/ImgVocabulario/Objects/pan.jpg'),
    },
    {
        id: '5',
        audio: require('../../audios/Vocabulario/objects/Pen.m4a') ,
        palavra: 'Pen',
        pronuncia: `/Pen/` ,
        img: require('../../images/ImgVocabulario/Objects/pen.jpg'),
    },
    {
        id: '6',
        audio: require('../../audios/Vocabulario/objects/Sofa.m4a') ,
        palavra: 'Sofa',
        pronuncia: `/ˈsoʊ.fə/` ,
        img: require('../../images/ImgVocabulario/Objects/sofa.jpg'),
    },
    {
        id: '7',
        audio: require('../../audios/Vocabulario/objects/Bed.m4a') ,
        palavra: 'Bed',
        pronuncia: `/ˈbed/` ,
        img: require('../../images/ImgVocabulario/Objects/bed.jpg'),
    },
    {
        id: '8',
        audio: require('../../audios/Vocabulario/objects/Table.m4a') ,
        palavra: 'Table',
        pronuncia: `/teɪ.bəl/` ,
        img: require('../../images/ImgVocabulario/Objects/table.jpg'),
    },
    {
        id: '9',
        audio: require('../../audios/Vocabulario/objects/Television.m4a') ,
        palavra: 'Television',
        pronuncia: `/ˈtel.ə.vɪʒ.ən/`,
        img: require('../../images/ImgVocabulario/Objects/television.jpg'),
    },
    {
        id: '10',
        audio: require('../../audios/Vocabulario/objects/Ball.m4a') ,
        palavra: 'Ball',
        pronuncia: `/bɑːl/`,
        img: require('../../images/ImgVocabulario/Objects/ball.png'),
    },
    
];

//fazer o mesmo com o restante...o ID sempre vai ser de 1 a 10